package inventory.model;
// Generated Jun 17, 2019 6:47:01 AM by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * Auth generated by hbm2java
 */
public class Auth implements java.io.Serializable {

	private Integer id;
	private Menu menu;
	private Role role;
	private int premission;
	private int activeLag;
	private Date createDate;
	private Date updateDate;

	public Auth() {
	}

	public Auth(Menu menu, Role role, int premission, int activeLag, Date createDate, Date updateDate) {
		this.menu = menu;
		this.role = role;
		this.premission = premission;
		this.activeLag = activeLag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public int getPremission() {
		return this.premission;
	}

	public void setPremission(int premission) {
		this.premission = premission;
	}

	public int getActiveLag() {
		return this.activeLag;
	}

	public void setActiveLag(int activeLag) {
		this.activeLag = activeLag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
