package inventory.model;
// Generated Jun 17, 2019 6:47:01 AM by Hibernate Tools 5.4.2.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private Integer id;
	private ProductInfo productInfo;
	private String code;
	private int type;
	private int qty;
	private BigDecimal price;
	private int activeLag;
	private Date createDate;
	private Date updateDate;

	public Invoice() {
	}

	public Invoice(ProductInfo productInfo, String code, int type, int qty, BigDecimal price, int activeLag,
			Date createDate, Date updateDate) {
		this.productInfo = productInfo;
		this.code = code;
		this.type = type;
		this.qty = qty;
		this.price = price;
		this.activeLag = activeLag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProductInfo getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(ProductInfo productInfo) {
		this.productInfo = productInfo;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public int getActiveLag() {
		return this.activeLag;
	}

	public void setActiveLag(int activeLag) {
		this.activeLag = activeLag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
