package inventory.model;
// Generated Jun 17, 2019 6:47:01 AM by Hibernate Tools 5.4.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer id;
	private int parent;
	private String url;
	private String name;
	private int orderIndex;
	private int activeLag;
	private Date createDate;
	private Date updateDate;
	private Set auths = new HashSet(0);
	private List<Menu> child;
	private String idMenu;

	public Menu() {
	}

	public Menu(int parent, String url, String name, int orderIndex, int activeLag, Date createDate, Date updateDate) {
		this.parent = parent;
		this.url = url;
		this.name = name;
		this.orderIndex = orderIndex;
		this.activeLag = activeLag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Menu(int parent, String url, String name, int orderIndex, int activeLag, Date createDate, Date updateDate,
			Set auths) {
		this.parent = parent;
		this.url = url;
		this.name = name;
		this.orderIndex = orderIndex;
		this.activeLag = activeLag;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.auths = auths;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getParent() {
		return this.parent;
	}

	public void setParent(int parent) {
		this.parent = parent;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getOrderIndex() {
		return this.orderIndex;
	}

	public void setOrderIndex(int orderIndex) {
		this.orderIndex = orderIndex;
	}

	public int getActiveLag() {
		return this.activeLag;
	}

	public void setActiveLag(int activeLag) {
		this.activeLag = activeLag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getAuths() {
		return this.auths;
	}

	public void setAuths(Set auths) {
		this.auths = auths;
	}

	public List<Menu> getChild() {
		return child;
	}

	public void setChild(List<Menu> child) {
		this.child = child;
	}

	public String getIdMenu() {
		return idMenu;
	}

	public void setIdMenu(String idMenu) {
		this.idMenu = idMenu;
	}
	

}
